export const ADD_POST = "ADD_POST"
export const DELETE_POST = "DELETE_POST"
export const EDIT_POST = "EDIT_POST"
export const NEW_POST = "NEW_POST"
export const DETAIL_POST = "DETAIL_POST"
export const SET_ALL_POSTS = "SET_ALL_POSTS"
export const MAKE_NEW_POST = "MAKE_NEW_POST"